services:
  scripts:
    build:
      context: .
    ports:
      - 8501:8501

    # platform: linux/amd64 # for m1 mac
    command:
      ["streamlit","run","app.py", "--server.port=8501", "--server.address=0.0.0.0"]
      